//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CompletionEqrSignOff struct {
	ID                                                  string `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	EngagementID                                        string // (DC2Type:guid)
	NodeID                                              string
	EntityStatus                                        *string
	SignificantRisksNotedDuringPlanningAndResponses     *string
	JudgementsMadeInRespectOfMaterial                   *string
	EvaluateWhetherAppropriateConsultation              *string
	FraudRiskPotentialBreachOfLaws                      *string
	CorrectedAndUncorrectedMisstatements                *string
	MattersToBeCommunicatedToManagement                 *string
	WhetherAuditDocumentationReviewed                   *string
	TheAppropriatenessOfTheAuditReportToBeIssued        *string
	TheScheduleOfUncorrectedMisstatements               *string
	ConsiderationOfFindingsArisingFrom                  *string
	IAgreeWithAllTheStatementsBelow                     *bool
	IConfirmThatIHaveReviewedTheFinalMateriality        *bool
	IConfirmThatIHaveReviewedTheFinalMaterialityComment *string
	AllProceduresRequiredByTheFirmsPolicies             *bool
	AllProceduresRequiredByTheFirmsPoliciesComment      *string
	IConfirmAppropriateConsultationHasTakenPlace        *bool
	IConfirmAppropriateConsultationHasTakenPlaceComment *string
	RelevantDocumentationRelatingToSignificant          *bool
	RelevantDocumentationRelatingToSignificantComment   *string
	IfAsPartOfTheAuditWeHaveIdentified                  *bool
	IfAsPartOfTheAuditWeHaveIdentifiedComment           *string
	AnyDifferencesOfOpinionBetweenTheAuditTeam          *bool
	AnyDifferencesOfOpinionBetweenTheAuditTeamComment   *string
	IHaveCompletedMyReviewAfterTheEngagement            *bool
	IHaveCompletedMyReviewAfterTheEngagementComment     *string
	IAmNotAwareOfAnyUnresolvedMatters                   *bool
	IAmNotAwareOfAnyUnresolvedMattersComment            *string
	TheRecommendedAuditReportHasBeenReviewed            *bool
	TheRecommendedAuditReportHasBeenReviewedComment     *string
	TheFinalDraftFinancialStatements                    *bool
	TheFinalDraftFinancialStatementsComment             *string
	IConfirmThatIRemainObjectiveAndIndependent          *bool
	IConfirmThatIRemainObjectiveAndIndependentComment   *string
	IConfirmThatTheBasisForTheEngagement                *bool
	IConfirmThatTheBasisForTheEngagementComment         *string
	IConfirmThatEngagementPartner                       *bool
	IConfirmThatEngagementPartnerComment                *string
	IConfirmThatAcceptanceOfReappointment               *bool
	IConfirmThatAcceptanceOfReappointmentComment        *string
	DoYouConfirmThatYouHavePerformedAnObjective         *bool
	DoYouConfirmThatYouHavePerformedAnObjectiveComment  *string
	DoYouConfirmThatYouHavePerformedTheReview           *bool
	DoYouConfirmThatYouHavePerformedTheReviewComment    *string
	IsValid                                             bool
	IAgreeWithAllTheStatementsBelowComment              *string
	HasBeenSubmittedForReview                           *bool
}
