//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Contacts struct {
	ID                 string `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	LastName           string
	FirstName          string
	Email              *string
	PrimaryPhoneNumber *string
	OtherPhoneNumber   *string
	DefaultCountryCode *string
}
