//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type CotabsAssertions struct {
	ID                string `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	CotabID           string // (DC2Type:guid)
	AssertionType     string
	Likelihood        *string
	Magnitude         *string
	ControlRisk       *string
	InherentRisk      *string
	Rmm               *string
	LikelihoodComment *string
}
