//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type DmsCallbackCorrelation struct {
	ID                 string    `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	CreatedAt          time.Time // (DC2Type:datetime_immutable)
	Action             string
	Parameters         *string    // (DC2Type:array)
	CallbackReceivedAt *time.Time // (DC2Type:datetime_immutable)
	IsFirstCall        bool
	Status             string
	MissingParameters  *string // (DC2Type:array)
}
