//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type EngagementDeletionRequests struct {
	ID                  string  `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	EngagementID        string  // (DC2Type:guid)
	InitiatedBy         string  // (DC2Type:guid)
	ApprovedBy          *string // (DC2Type:guid)
	ReasonForDeletionID *int32
	AdditionalComment   *string
	InitiatedOn         time.Time
	ApprovedOn          *time.Time
	ReasonForRejection  *string
	State               string
	TypeOfRequest       *string
}
