//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type EngagementOverallResponse struct {
	ID                                   string `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	EngagementID                         string // (DC2Type:guid)
	EmphasizeEngagementTeam              *bool
	EmphasizeEngagementTeamComment       string
	AssignMoreStaff                      *bool
	AssignMoreStaffComment               string
	ProvideMoreSupervision               *bool
	ProvideMoreSupervisionComment        string
	IncorporateAdditionalElements        *bool
	IncorporateAdditionalElementsComment string
	MakeGeneralChanges                   *bool
	MakeGeneralChangesComment            string
	IsValid                              bool
}
