//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type EngagementControlEnvironment struct {
	ID                                        string `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	EngagementID                              string // (DC2Type:guid)
	HowManagementOversightResponsibilities    string
	WhenThoseChargedWithGovernance            string
	EntityAssignmentOfAuthorityResponsibility string
	HowEntityAttractsDevelopsRetains          string
	HowEntityHoldsIndividualsAccountable      string
	OngoingSeparateEvaluations                string
	DescribeSourcesOfInformation              string
	EvaluateWhetherManagement                 string
	EvaluateWhetherStrengths                  string
	EntityProcessForMonitoringSystem          string
	IsValid                                   bool
	DoesEntityUseServiceOrganisations         *bool
	DoesEntityHaveInternalAuditFunction       *bool
}
