//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type EngagementTeamMembers struct {
	ID                                 string `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	MemberID                           string // (DC2Type:guid)
	RoleWithinTeam                     *string
	IndustryKnowledgeAndLicenseDetails *string
	YearAppointedToTeam                *time.Time // (DC2Type:datetime_immutable)
	Signatory                          *bool
	AccessToFile                       *bool
	CreatedAt                          *time.Time // (DC2Type:datetime_immutable)
}
