//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Engagements struct {
	ID                                                  string  `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	CreatedBy                                           *string // (DC2Type:guid)
	CreatedAt                                           time.Time
	UpdatedAt                                           *time.Time
	Entity                                              *string // (DC2Type:guid)
	LeadPartner                                         *string // (DC2Type:guid)
	ReviewAccessAssignedBy                              *string // (DC2Type:guid)
	EntityStatus                                        *string
	Type                                                *string
	PeriodEndDate                                       *time.Time // (DC2Type:datetime_immutable)
	TypeOfService                                       *string
	DescriptionOfEngagement                             *string
	LocalPackage                                        string
	Name                                                *string
	Status                                              *string
	PeriodCommencingDate                                *time.Time // (DC2Type:datetime_immutable)
	Office                                              *string
	ManagementUnit                                      *string
	Sector                                              *string
	SubSector                                           *string
	IsMultiYear                                         *bool
	ExpectedEndOfTerm                                   *time.Time // (DC2Type:date_immutable)
	TestEngagementCategory                              *string
	BackOfficeJobNumber                                 *string
	RegulatorNumber                                     *string
	WonThroughTender                                    *bool
	DateOfRenewal                                       *time.Time // (DC2Type:datetime_immutable)
	IsFirstYearAudit                                    *bool
	FirstAssignmentPeriodEndDate                        *time.Time // (DC2Type:datetime_immutable)
	WasTheEntityEstablishedInThisPeriod                 *bool
	WasTheEntityExemptFromAuditInThePriorPeriod         *bool
	PredecessorAuditor                                  *string // (DC2Type:array)
	OtherPredecessorAuditor                             *string // (DC2Type:array)
	HaveYouCommunicatedWithThePredecessorAuditor        *bool
	CommunicationDetails                                *string
	WasThereAnyModificationToTheOpinionInThePriorPeriod *bool
	ExplanationOfModification                           *string
	IsJointAudit                                        *bool
	JointAuditor                                        *string
	OtherJointAuditor                                   *string
	JointAuditorAddress                                 *string
	JointAuditAssignmentDate                            *time.Time // (DC2Type:datetime_immutable)
	PartnerName1                                        *string
	PartnerName2                                        *string
	FunctionalCurrency                                  *string
	PresentationalCurrency                              *string
	AccountingFramework                                 *string
	PreviousAccountingFramework                         *string
	DocumentWhetherSelectedFrameworkIsAcceptable        *string
	ReasonForChangeOfAccountingFramework                *string
	ExpectedShareholderMeetingDate                      *time.Time // (DC2Type:datetime_immutable)
	NumberOfDaysBeforeLockdown                          int32
	Events                                              *string // (DC2Type:array)
	AgreedFee                                           *float64
	FeeCurrency                                         *string
	AreYouAGroupAuditorUnderIsa600                      *bool
	WillYouRelyOnTheWorkOfComponentAuditors             *bool
	AreYouRequiredToIssueALimitedReviewReport           *bool
	SelectRequiredLimitedReviewReports                  *string // (DC2Type:array)
	AreYouAComponentAuditor                             *bool
	AreYouRequiredToIssueAnOpinion                      *bool
	SelectRequiredOpinions                              *string // (DC2Type:array)
	ArePcaobRequirementsRelevantToThisEngagement        *bool
	AreUsReportingRequirementsRelevantToThisEngagement  *bool
	ReviewAccessRemovalDate                             *time.Time // (DC2Type:date_immutable)
	IsEqcrRequired                                      *bool
	DetailOfConsiderationOfTheNeedForAnEqcr             *string
	DeletionState                                       *string
	PackageToTestIdentifier                             *string
	PackageToTestVersion                                *string
	PackageToTestLastCommit                             *string
	LatestLocalPackage                                  *string
	IsMigrated                                          *bool
	Risk                                                *bool
	ChecklistIDCauseRisky                               *string
	HasAccountingFrameworkChangedSincePriorPeriod       *bool
	AcceptanceSurveyRisky                               *bool
	LockdownDate                                        *time.Time
	UnlockDate                                          *time.Time
	IsFromLocked                                        bool
	EngagementRollforwardSource                         *string // @JsonFormat(property="id") @JsonInclude(DC2Type:guid)
}
