//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type MasterEntities struct {
	ID                                 string  `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	ParentEntity                       *string // (DC2Type:guid)
	LeadPartnerID                      *string // (DC2Type:guid)
	TypeID                             *int32
	CountryCode                        *string
	Name                               *string
	AbbreviatedName                    *string
	BranchSscName                      *string
	StatusID                           *int32
	TestEntityCategoryID               *int32
	PrimaryAddress                     *string
	PrimaryCity                        *string
	PrimaryStateProvinceCountry        *string
	PrimaryPostalCode                  *string
	PrimaryPhoneNumber                 *string
	PrimaryOtherPhoneNumber            *string
	SecondaryAddress                   *string
	SecondaryCity                      *string
	SecondaryStateProvinceCountry      *string
	SecondaryPostalCode                *string
	SecondaryPhoneNumber               *string
	SecondaryOtherPhoneNumber          *string
	HasNationalRegistration            *bool
	NationalRegistrationNumber         *string
	UniqueGlobalNumber                 *string
	Description                        *string
	LegalFormID                        *int32
	DescriptionOfActivity              *string
	ListedCompany                      *bool
	StockExchangeListing               *string // (DC2Type:array)
	CountriesOfListingCodes            *string // (DC2Type:array)
	Pie                                *bool
	OtherRelevantServicesProvidedBySsc *string // (DC2Type:array)
	PeriodEndDate                      *time.Time
	HasPreparingConsolidatedAccounts   *bool
	HasBusinessDivisions               *bool
	HasBranches                        *bool
	HasSharedServicesCentres           *bool
	FrequencyOfConsolidation           *string
	NumberOfEmployees                  *string
	IsMigrated                         *bool
	PackageToTestIdentifier            *string
	PackageToTestVersion               *string
	PackageToTestLastCommitHash        *string
	IsValid                            *bool
	Locked                             bool
	LockedAt                           *time.Time // (DC2Type:date_immutable)
	Deleted                            int32
}
