//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type OtherFslrBusinessRisks struct {
	ID             string `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	Name           *string
	Description    *string
	EngagementID   string // (DC2Type:guid)
	CreatedAt      *time.Time
	IsDeleted      *bool
	BusinessRiskID *string // (DC2Type:guid)
}
