//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type OtherFslrForms struct {
	ID                                                      string `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	EngagementID                                            string // (DC2Type:guid)
	NodeID                                                  string
	HaveIdentifiedAnyOtherFslr                              *bool
	DoYouIntendToRelyOnInternalControl                      *bool
	WillSubstantiveProceduresProvideSufficientAuditEvidence *bool
	HasManagementImplementedControlOverTheRisk              *bool
	NeedToEmphasizeToTheEngagementTeam                      *bool
	NeedToEmphasizeToTheEngagementTeamComment               *string
	NeedToAssignMoreExperiencedStaff                        *bool
	NeedToAssignMoreExperiencedStaffComment                 *string
	NeedToProvideMoreSupervision                            *bool
	NeedToProvideMoreSupervisionComment                     *string
	NeedToIncorporateAdditionalElements                     *bool
	NeedToIncorporateAdditionalElementsComment              *string
	NeedToMakeGeneralChangesToNatureTiming                  *bool
	NeedToMakeGeneralChangesToNatureTimingComment           *string
	UseOfAnExpertRequired                                   *bool
	Status                                                  *string
	IsAtLeastOneControlEvaluatedToDi                        *bool
	IsAtLeastOneControlEvaluatedToOe                        *bool
}
