//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type RelatedParties struct {
	ID                                               string `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	EngagementMasterfileNodeID                       string // (DC2Type:guid)
	Name                                             string
	NatureOfRelationship                             *string
	AnyTransactionsEntered                           *bool
	AnyOfTheseTransactionsDeemedSignificant          *bool
	TypeAndPurposeOfTransaction                      *string
	DetailsOfSignificantTransactions                 *string
	HasManagementMadeAnAssertion                     *bool
	DetailsOfTransactionsConsideredToBeEquivalent    *string
	DetailsOfTransactionsConsideredNotToBeEquivalent *string
	IsValid                                          bool
}
