//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Reviews struct {
	Reviewer              string     `sql:"primary_key"` // (DC2Type:guid)
	Engagement            string     `sql:"primary_key"` // (DC2Type:guid)
	StartDate             *time.Time // (DC2Type:date_immutable)
	EndDate               *time.Time // (DC2Type:date_immutable)
	BaseCountryCode       string
	MaxPeriodAfterEndDate *time.Time // (DC2Type:date_immutable)
	ReviewerRole          string
	AllowedNotes          *string // (DC2Type:array)
	AllowedAuditTrail     *bool
}
