//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type RevisedMateriality struct {
	ID                                             string `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	PlanningMaterialityID                          string // (DC2Type:guid)
	EntityStatus                                   *string
	BasisOrAmountCalculationChanged                *bool
	Rationale                                      *string
	BasisLovID                                     *string
	OtherBasisName                                 *string
	FiguresBelowDisplayedInLovID                   *string
	FinancialStatementQuantum                      *float64
	FinancialStatementPercentageSelected           *float64
	FinancialStatementRationale                    *string
	ChosenFinancialStatementMateriality            *float64
	PerformanceStatementPercentageSelected         *float64
	PerformanceStatementRationale                  *string
	ChosenPerformanceMateriality                   *float64
	ClearlyTrivialThresholdPercentageSelectedLovID *string
	ChosenClearlyTrivialThreshold                  *float64
	UpdateAreasID                                  *string
	Explanation                                    *string
	ApplyAcrossTheAuditFile                        *bool
	SelectedBenchmark                              *string
	NodeID                                         *string
	PeriodEndOfSourceDataUsed                      *time.Time // (DC2Type:datetime_immutable)
	RationaleRelatingToBenchmark                   *string
	HeaderRationale                                *string
	IsBasisOrAmountCalculationChangedReadonly      *bool
}
