//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type RiskControlDetails struct {
	ID                    string `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	ControlID             string // (DC2Type:guid)
	ControlType           *string
	ControlFrequency      *string
	PreventOrDetect       *string
	PlannedEvaluationDi   *bool
	PlannedEvaluationOe   *bool
	ItApplicationSelected *bool
	ItApplicationID       *string
	ControlLevel          *string
	ControlDetailFormID   *string // (DC2Type:guid)
}
