//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type UsersManagementUnits struct {
	UserID           string `sql:"primary_key"` // (DC2Type:guid)
	ManagementUnitID string `sql:"primary_key"`
}
