//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

type Wcgw struct {
	ID                    string `sql:"primary_key"` // @UUID("v4")(DC2Type:guid)
	EngagementID          string // (DC2Type:guid)
	Name                  *string
	SourceID              *string
	OriginType            *string
	Type                  *string
	Status                *string
	Label                 *string // (DC2Type:json)
	DateLastLabelModified *string // (DC2Type:json)
	BusinessRisks         *string // (DC2Type:array)
}
