//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var AuditorsExperts = newAuditorsExpertsTable("atlas-blue", "auditors_experts", "")

type auditorsExpertsTable struct {
	mysql.Table

	// Columns
	ID                                          mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	EngagementID                                mysql.ColumnString // (DC2Type:guid)
	ExpertName                                  mysql.ColumnString
	FieldOfExpertise                            mysql.ColumnString
	NatureOfTheExpertsWork                      mysql.ColumnString
	SignificanceOfTheExpert                     mysql.ColumnString
	KnowledgeOfAndExperience                    mysql.ColumnString
	IsTheExpertAnAuditorsInternal               mysql.ColumnBool
	ExpertAnAuditorsInternalComment             mysql.ColumnString
	IsTheExpertSubjectToOurOwnInternalQuality   mysql.ColumnBool
	ExpertSubjectToOurOwnInternalQualityComment mysql.ColumnString
	EvaluateCompetenceAndCapabilities           mysql.ColumnString
	HaveYouInquiredOfInterestsRelationships     mysql.ColumnBool
	InquiredOfInterestsRelationshipsComment     mysql.ColumnString
	IsTheExpertObjective                        mysql.ColumnBool
	DescribeObjectivityIssues                   mysql.ColumnString
	NatureScopeObjectivesExpertsWork            mysql.ColumnString
	HaveAgreed                                  mysql.ColumnBool
	CommentOnAgreement                          mysql.ColumnString
	Status                                      mysql.ColumnString
	Deleted                                     mysql.ColumnInteger
	AnySafeguardsThatEliminateTheThreat         mysql.ColumnBool
	DescribeTheSafeguards                       mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type AuditorsExpertsTable struct {
	auditorsExpertsTable

	NEW auditorsExpertsTable
}

// AS creates new AuditorsExpertsTable with assigned alias
func (a AuditorsExpertsTable) AS(alias string) *AuditorsExpertsTable {
	return newAuditorsExpertsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new AuditorsExpertsTable with assigned schema name
func (a AuditorsExpertsTable) FromSchema(schemaName string) *AuditorsExpertsTable {
	return newAuditorsExpertsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new AuditorsExpertsTable with assigned table prefix
func (a AuditorsExpertsTable) WithPrefix(prefix string) *AuditorsExpertsTable {
	return newAuditorsExpertsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new AuditorsExpertsTable with assigned table suffix
func (a AuditorsExpertsTable) WithSuffix(suffix string) *AuditorsExpertsTable {
	return newAuditorsExpertsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newAuditorsExpertsTable(schemaName, tableName, alias string) *AuditorsExpertsTable {
	return &AuditorsExpertsTable{
		auditorsExpertsTable: newAuditorsExpertsTableImpl(schemaName, tableName, alias),
		NEW:                  newAuditorsExpertsTableImpl("", "new", ""),
	}
}

func newAuditorsExpertsTableImpl(schemaName, tableName, alias string) auditorsExpertsTable {
	var (
		IDColumn                                          = mysql.StringColumn("id")
		EngagementIDColumn                                = mysql.StringColumn("engagement_id")
		ExpertNameColumn                                  = mysql.StringColumn("expert_name")
		FieldOfExpertiseColumn                            = mysql.StringColumn("field_of_expertise")
		NatureOfTheExpertsWorkColumn                      = mysql.StringColumn("nature_of_the_experts_work")
		SignificanceOfTheExpertColumn                     = mysql.StringColumn("significance_of_the_expert")
		KnowledgeOfAndExperienceColumn                    = mysql.StringColumn("knowledge_of_and_experience")
		IsTheExpertAnAuditorsInternalColumn               = mysql.BoolColumn("is_the_expert_an_auditors_internal")
		ExpertAnAuditorsInternalCommentColumn             = mysql.StringColumn("expert_an_auditors_internal_comment")
		IsTheExpertSubjectToOurOwnInternalQualityColumn   = mysql.BoolColumn("is_the_expert_subject_to_our_own_internal_quality")
		ExpertSubjectToOurOwnInternalQualityCommentColumn = mysql.StringColumn("expert_subject_to_our_own_internal_quality_comment")
		EvaluateCompetenceAndCapabilitiesColumn           = mysql.StringColumn("evaluate_competence_and_capabilities")
		HaveYouInquiredOfInterestsRelationshipsColumn     = mysql.BoolColumn("have_you_inquired_of_interests_relationships")
		InquiredOfInterestsRelationshipsCommentColumn     = mysql.StringColumn("inquired_of_interests_relationships_comment")
		IsTheExpertObjectiveColumn                        = mysql.BoolColumn("is_the_expert_objective")
		DescribeObjectivityIssuesColumn                   = mysql.StringColumn("describe_objectivity_issues")
		NatureScopeObjectivesExpertsWorkColumn            = mysql.StringColumn("nature_scope_objectives_experts_work")
		HaveAgreedColumn                                  = mysql.BoolColumn("have_agreed")
		CommentOnAgreementColumn                          = mysql.StringColumn("comment_on_agreement")
		StatusColumn                                      = mysql.StringColumn("status")
		DeletedColumn                                     = mysql.IntegerColumn("deleted")
		AnySafeguardsThatEliminateTheThreatColumn         = mysql.BoolColumn("any_safeguards_that_eliminate_the_threat")
		DescribeTheSafeguardsColumn                       = mysql.StringColumn("describe_the_safeguards")
		allColumns                                        = mysql.ColumnList{IDColumn, EngagementIDColumn, ExpertNameColumn, FieldOfExpertiseColumn, NatureOfTheExpertsWorkColumn, SignificanceOfTheExpertColumn, KnowledgeOfAndExperienceColumn, IsTheExpertAnAuditorsInternalColumn, ExpertAnAuditorsInternalCommentColumn, IsTheExpertSubjectToOurOwnInternalQualityColumn, ExpertSubjectToOurOwnInternalQualityCommentColumn, EvaluateCompetenceAndCapabilitiesColumn, HaveYouInquiredOfInterestsRelationshipsColumn, InquiredOfInterestsRelationshipsCommentColumn, IsTheExpertObjectiveColumn, DescribeObjectivityIssuesColumn, NatureScopeObjectivesExpertsWorkColumn, HaveAgreedColumn, CommentOnAgreementColumn, StatusColumn, DeletedColumn, AnySafeguardsThatEliminateTheThreatColumn, DescribeTheSafeguardsColumn}
		mutableColumns                                    = mysql.ColumnList{EngagementIDColumn, ExpertNameColumn, FieldOfExpertiseColumn, NatureOfTheExpertsWorkColumn, SignificanceOfTheExpertColumn, KnowledgeOfAndExperienceColumn, IsTheExpertAnAuditorsInternalColumn, ExpertAnAuditorsInternalCommentColumn, IsTheExpertSubjectToOurOwnInternalQualityColumn, ExpertSubjectToOurOwnInternalQualityCommentColumn, EvaluateCompetenceAndCapabilitiesColumn, HaveYouInquiredOfInterestsRelationshipsColumn, InquiredOfInterestsRelationshipsCommentColumn, IsTheExpertObjectiveColumn, DescribeObjectivityIssuesColumn, NatureScopeObjectivesExpertsWorkColumn, HaveAgreedColumn, CommentOnAgreementColumn, StatusColumn, DeletedColumn, AnySafeguardsThatEliminateTheThreatColumn, DescribeTheSafeguardsColumn}
	)

	return auditorsExpertsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                              IDColumn,
		EngagementID:                    EngagementIDColumn,
		ExpertName:                      ExpertNameColumn,
		FieldOfExpertise:                FieldOfExpertiseColumn,
		NatureOfTheExpertsWork:          NatureOfTheExpertsWorkColumn,
		SignificanceOfTheExpert:         SignificanceOfTheExpertColumn,
		KnowledgeOfAndExperience:        KnowledgeOfAndExperienceColumn,
		IsTheExpertAnAuditorsInternal:   IsTheExpertAnAuditorsInternalColumn,
		ExpertAnAuditorsInternalComment: ExpertAnAuditorsInternalCommentColumn,
		IsTheExpertSubjectToOurOwnInternalQuality:   IsTheExpertSubjectToOurOwnInternalQualityColumn,
		ExpertSubjectToOurOwnInternalQualityComment: ExpertSubjectToOurOwnInternalQualityCommentColumn,
		EvaluateCompetenceAndCapabilities:           EvaluateCompetenceAndCapabilitiesColumn,
		HaveYouInquiredOfInterestsRelationships:     HaveYouInquiredOfInterestsRelationshipsColumn,
		InquiredOfInterestsRelationshipsComment:     InquiredOfInterestsRelationshipsCommentColumn,
		IsTheExpertObjective:                        IsTheExpertObjectiveColumn,
		DescribeObjectivityIssues:                   DescribeObjectivityIssuesColumn,
		NatureScopeObjectivesExpertsWork:            NatureScopeObjectivesExpertsWorkColumn,
		HaveAgreed:                                  HaveAgreedColumn,
		CommentOnAgreement:                          CommentOnAgreementColumn,
		Status:                                      StatusColumn,
		Deleted:                                     DeletedColumn,
		AnySafeguardsThatEliminateTheThreat:         AnySafeguardsThatEliminateTheThreatColumn,
		DescribeTheSafeguards:                       DescribeTheSafeguardsColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
