//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var ContactGroups = newContactGroupsTable("atlas-blue", "contact_groups", "")

type contactGroupsTable struct {
	mysql.Table

	// Columns
	ID              mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	GroupID         mysql.ColumnString // (DC2Type:guid)
	ContactID       mysql.ColumnString // (DC2Type:guid)
	Tcwg            mysql.ColumnString
	JobTitle        mysql.ColumnString
	AppointmentDate mysql.ColumnDate
	CessationDate   mysql.ColumnDate

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type ContactGroupsTable struct {
	contactGroupsTable

	NEW contactGroupsTable
}

// AS creates new ContactGroupsTable with assigned alias
func (a ContactGroupsTable) AS(alias string) *ContactGroupsTable {
	return newContactGroupsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ContactGroupsTable with assigned schema name
func (a ContactGroupsTable) FromSchema(schemaName string) *ContactGroupsTable {
	return newContactGroupsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ContactGroupsTable with assigned table prefix
func (a ContactGroupsTable) WithPrefix(prefix string) *ContactGroupsTable {
	return newContactGroupsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ContactGroupsTable with assigned table suffix
func (a ContactGroupsTable) WithSuffix(suffix string) *ContactGroupsTable {
	return newContactGroupsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newContactGroupsTable(schemaName, tableName, alias string) *ContactGroupsTable {
	return &ContactGroupsTable{
		contactGroupsTable: newContactGroupsTableImpl(schemaName, tableName, alias),
		NEW:                newContactGroupsTableImpl("", "new", ""),
	}
}

func newContactGroupsTableImpl(schemaName, tableName, alias string) contactGroupsTable {
	var (
		IDColumn              = mysql.StringColumn("id")
		GroupIDColumn         = mysql.StringColumn("group_id")
		ContactIDColumn       = mysql.StringColumn("contact_id")
		TcwgColumn            = mysql.StringColumn("tcwg")
		JobTitleColumn        = mysql.StringColumn("job_title")
		AppointmentDateColumn = mysql.DateColumn("appointment_date")
		CessationDateColumn   = mysql.DateColumn("cessation_date")
		allColumns            = mysql.ColumnList{IDColumn, GroupIDColumn, ContactIDColumn, TcwgColumn, JobTitleColumn, AppointmentDateColumn, CessationDateColumn}
		mutableColumns        = mysql.ColumnList{GroupIDColumn, ContactIDColumn, TcwgColumn, JobTitleColumn, AppointmentDateColumn, CessationDateColumn}
	)

	return contactGroupsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:              IDColumn,
		GroupID:         GroupIDColumn,
		ContactID:       ContactIDColumn,
		Tcwg:            TcwgColumn,
		JobTitle:        JobTitleColumn,
		AppointmentDate: AppointmentDateColumn,
		CessationDate:   CessationDateColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
