//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var EngagementMasterfileNodesRestore = newEngagementMasterfileNodesRestoreTable("atlas-blue", "engagement_masterfile_nodes_restore", "")

type engagementMasterfileNodesRestoreTable struct {
	mysql.Table

	// Columns
	ID                   mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	EngagementID         mysql.ColumnString // (DC2Type:guid)
	SubmittedBy          mysql.ColumnString // (DC2Type:guid)
	NodeID               mysql.ColumnString
	Status               mysql.ColumnString
	Note                 mysql.ColumnString
	FirstSubmittedBy     mysql.ColumnString    // (DC2Type:guid)
	LastSubmittedDate    mysql.ColumnTimestamp // (DC2Type:datetime_immutable)
	TypeOfNotesRaised    mysql.ColumnString    // (DC2Type:array)
	IsMisstatementRaised mysql.ColumnBool
	Warnings             mysql.ColumnString
	IsFirstReview        mysql.ColumnBool
	AreaName             mysql.ColumnString
	SectionName          mysql.ColumnString
	LastSubmitterRole    mysql.ColumnString
	LastReviewerRole     mysql.ColumnString
	ReviewedByEqr        mysql.ColumnBool
	SubmitConflict       mysql.ColumnBool
	ReviewConflict       mysql.ColumnBool
	EqrConflict          mysql.ColumnBool
	FirstSubmitterRole   mysql.ColumnString
	FirstSubmittedDate   mysql.ColumnTimestamp // (DC2Type:datetime_immutable)
	ConflictFromDocument mysql.ColumnBool

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type EngagementMasterfileNodesRestoreTable struct {
	engagementMasterfileNodesRestoreTable

	NEW engagementMasterfileNodesRestoreTable
}

// AS creates new EngagementMasterfileNodesRestoreTable with assigned alias
func (a EngagementMasterfileNodesRestoreTable) AS(alias string) *EngagementMasterfileNodesRestoreTable {
	return newEngagementMasterfileNodesRestoreTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EngagementMasterfileNodesRestoreTable with assigned schema name
func (a EngagementMasterfileNodesRestoreTable) FromSchema(schemaName string) *EngagementMasterfileNodesRestoreTable {
	return newEngagementMasterfileNodesRestoreTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EngagementMasterfileNodesRestoreTable with assigned table prefix
func (a EngagementMasterfileNodesRestoreTable) WithPrefix(prefix string) *EngagementMasterfileNodesRestoreTable {
	return newEngagementMasterfileNodesRestoreTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EngagementMasterfileNodesRestoreTable with assigned table suffix
func (a EngagementMasterfileNodesRestoreTable) WithSuffix(suffix string) *EngagementMasterfileNodesRestoreTable {
	return newEngagementMasterfileNodesRestoreTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEngagementMasterfileNodesRestoreTable(schemaName, tableName, alias string) *EngagementMasterfileNodesRestoreTable {
	return &EngagementMasterfileNodesRestoreTable{
		engagementMasterfileNodesRestoreTable: newEngagementMasterfileNodesRestoreTableImpl(schemaName, tableName, alias),
		NEW:                                   newEngagementMasterfileNodesRestoreTableImpl("", "new", ""),
	}
}

func newEngagementMasterfileNodesRestoreTableImpl(schemaName, tableName, alias string) engagementMasterfileNodesRestoreTable {
	var (
		IDColumn                   = mysql.StringColumn("id")
		EngagementIDColumn         = mysql.StringColumn("engagement_id")
		SubmittedByColumn          = mysql.StringColumn("submitted_by")
		NodeIDColumn               = mysql.StringColumn("node_id")
		StatusColumn               = mysql.StringColumn("status")
		NoteColumn                 = mysql.StringColumn("note")
		FirstSubmittedByColumn     = mysql.StringColumn("first_submitted_by")
		LastSubmittedDateColumn    = mysql.TimestampColumn("last_submitted_date")
		TypeOfNotesRaisedColumn    = mysql.StringColumn("type_of_notes_raised")
		IsMisstatementRaisedColumn = mysql.BoolColumn("is_misstatement_raised")
		WarningsColumn             = mysql.StringColumn("warnings")
		IsFirstReviewColumn        = mysql.BoolColumn("is_first_review")
		AreaNameColumn             = mysql.StringColumn("area_name")
		SectionNameColumn          = mysql.StringColumn("section_name")
		LastSubmitterRoleColumn    = mysql.StringColumn("last_submitter_role")
		LastReviewerRoleColumn     = mysql.StringColumn("last_reviewer_role")
		ReviewedByEqrColumn        = mysql.BoolColumn("reviewed_by_eqr")
		SubmitConflictColumn       = mysql.BoolColumn("submit_conflict")
		ReviewConflictColumn       = mysql.BoolColumn("review_conflict")
		EqrConflictColumn          = mysql.BoolColumn("eqr_conflict")
		FirstSubmitterRoleColumn   = mysql.StringColumn("first_submitter_role")
		FirstSubmittedDateColumn   = mysql.TimestampColumn("first_submitted_date")
		ConflictFromDocumentColumn = mysql.BoolColumn("conflict_from_document")
		allColumns                 = mysql.ColumnList{IDColumn, EngagementIDColumn, SubmittedByColumn, NodeIDColumn, StatusColumn, NoteColumn, FirstSubmittedByColumn, LastSubmittedDateColumn, TypeOfNotesRaisedColumn, IsMisstatementRaisedColumn, WarningsColumn, IsFirstReviewColumn, AreaNameColumn, SectionNameColumn, LastSubmitterRoleColumn, LastReviewerRoleColumn, ReviewedByEqrColumn, SubmitConflictColumn, ReviewConflictColumn, EqrConflictColumn, FirstSubmitterRoleColumn, FirstSubmittedDateColumn, ConflictFromDocumentColumn}
		mutableColumns             = mysql.ColumnList{EngagementIDColumn, SubmittedByColumn, NodeIDColumn, StatusColumn, NoteColumn, FirstSubmittedByColumn, LastSubmittedDateColumn, TypeOfNotesRaisedColumn, IsMisstatementRaisedColumn, WarningsColumn, IsFirstReviewColumn, AreaNameColumn, SectionNameColumn, LastSubmitterRoleColumn, LastReviewerRoleColumn, ReviewedByEqrColumn, SubmitConflictColumn, ReviewConflictColumn, EqrConflictColumn, FirstSubmitterRoleColumn, FirstSubmittedDateColumn, ConflictFromDocumentColumn}
	)

	return engagementMasterfileNodesRestoreTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                   IDColumn,
		EngagementID:         EngagementIDColumn,
		SubmittedBy:          SubmittedByColumn,
		NodeID:               NodeIDColumn,
		Status:               StatusColumn,
		Note:                 NoteColumn,
		FirstSubmittedBy:     FirstSubmittedByColumn,
		LastSubmittedDate:    LastSubmittedDateColumn,
		TypeOfNotesRaised:    TypeOfNotesRaisedColumn,
		IsMisstatementRaised: IsMisstatementRaisedColumn,
		Warnings:             WarningsColumn,
		IsFirstReview:        IsFirstReviewColumn,
		AreaName:             AreaNameColumn,
		SectionName:          SectionNameColumn,
		LastSubmitterRole:    LastSubmitterRoleColumn,
		LastReviewerRole:     LastReviewerRoleColumn,
		ReviewedByEqr:        ReviewedByEqrColumn,
		SubmitConflict:       SubmitConflictColumn,
		ReviewConflict:       ReviewConflictColumn,
		EqrConflict:          EqrConflictColumn,
		FirstSubmitterRole:   FirstSubmitterRoleColumn,
		FirstSubmittedDate:   FirstSubmittedDateColumn,
		ConflictFromDocument: ConflictFromDocumentColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
