//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var EngagementsAuditTrails = newEngagementsAuditTrailsTable("atlas-blue", "engagements_audit_trails", "")

type engagementsAuditTrailsTable struct {
	mysql.Table

	// Columns
	ID             mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	EngagementID   mysql.ColumnString // (DC2Type:guid)
	UserID         mysql.ColumnString // (DC2Type:guid)
	PackageID      mysql.ColumnString
	OccurredAt     mysql.ColumnTimestamp
	NodeID         mysql.ColumnString
	Tab            mysql.ColumnString
	Fieldset       mysql.ColumnString
	Field          mysql.ColumnString
	Action         mysql.ColumnString
	OtherReference mysql.ColumnString
	PreviousValue  mysql.ColumnString
	NewValue       mysql.ColumnString
	FormID         mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type EngagementsAuditTrailsTable struct {
	engagementsAuditTrailsTable

	NEW engagementsAuditTrailsTable
}

// AS creates new EngagementsAuditTrailsTable with assigned alias
func (a EngagementsAuditTrailsTable) AS(alias string) *EngagementsAuditTrailsTable {
	return newEngagementsAuditTrailsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new EngagementsAuditTrailsTable with assigned schema name
func (a EngagementsAuditTrailsTable) FromSchema(schemaName string) *EngagementsAuditTrailsTable {
	return newEngagementsAuditTrailsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new EngagementsAuditTrailsTable with assigned table prefix
func (a EngagementsAuditTrailsTable) WithPrefix(prefix string) *EngagementsAuditTrailsTable {
	return newEngagementsAuditTrailsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new EngagementsAuditTrailsTable with assigned table suffix
func (a EngagementsAuditTrailsTable) WithSuffix(suffix string) *EngagementsAuditTrailsTable {
	return newEngagementsAuditTrailsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newEngagementsAuditTrailsTable(schemaName, tableName, alias string) *EngagementsAuditTrailsTable {
	return &EngagementsAuditTrailsTable{
		engagementsAuditTrailsTable: newEngagementsAuditTrailsTableImpl(schemaName, tableName, alias),
		NEW:                         newEngagementsAuditTrailsTableImpl("", "new", ""),
	}
}

func newEngagementsAuditTrailsTableImpl(schemaName, tableName, alias string) engagementsAuditTrailsTable {
	var (
		IDColumn             = mysql.StringColumn("id")
		EngagementIDColumn   = mysql.StringColumn("engagement_id")
		UserIDColumn         = mysql.StringColumn("user_id")
		PackageIDColumn      = mysql.StringColumn("package_id")
		OccurredAtColumn     = mysql.TimestampColumn("occurred_at")
		NodeIDColumn         = mysql.StringColumn("node_id")
		TabColumn            = mysql.StringColumn("tab")
		FieldsetColumn       = mysql.StringColumn("fieldset")
		FieldColumn          = mysql.StringColumn("field")
		ActionColumn         = mysql.StringColumn("action")
		OtherReferenceColumn = mysql.StringColumn("other_reference")
		PreviousValueColumn  = mysql.StringColumn("previous_value")
		NewValueColumn       = mysql.StringColumn("new_value")
		FormIDColumn         = mysql.StringColumn("form_id")
		allColumns           = mysql.ColumnList{IDColumn, EngagementIDColumn, UserIDColumn, PackageIDColumn, OccurredAtColumn, NodeIDColumn, TabColumn, FieldsetColumn, FieldColumn, ActionColumn, OtherReferenceColumn, PreviousValueColumn, NewValueColumn, FormIDColumn}
		mutableColumns       = mysql.ColumnList{EngagementIDColumn, UserIDColumn, PackageIDColumn, OccurredAtColumn, NodeIDColumn, TabColumn, FieldsetColumn, FieldColumn, ActionColumn, OtherReferenceColumn, PreviousValueColumn, NewValueColumn, FormIDColumn}
	)

	return engagementsAuditTrailsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		EngagementID:   EngagementIDColumn,
		UserID:         UserIDColumn,
		PackageID:      PackageIDColumn,
		OccurredAt:     OccurredAtColumn,
		NodeID:         NodeIDColumn,
		Tab:            TabColumn,
		Fieldset:       FieldsetColumn,
		Field:          FieldColumn,
		Action:         ActionColumn,
		OtherReference: OtherReferenceColumn,
		PreviousValue:  PreviousValueColumn,
		NewValue:       NewValueColumn,
		FormID:         FormIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
