//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var GoingConcernFinalConclusion = newGoingConcernFinalConclusionTable("atlas-blue", "going_concern_final_conclusion", "")

type goingConcernFinalConclusionTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	EngagementID mysql.ColumnString // (DC2Type:guid)
	IsValid      mysql.ColumnBool

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type GoingConcernFinalConclusionTable struct {
	goingConcernFinalConclusionTable

	NEW goingConcernFinalConclusionTable
}

// AS creates new GoingConcernFinalConclusionTable with assigned alias
func (a GoingConcernFinalConclusionTable) AS(alias string) *GoingConcernFinalConclusionTable {
	return newGoingConcernFinalConclusionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GoingConcernFinalConclusionTable with assigned schema name
func (a GoingConcernFinalConclusionTable) FromSchema(schemaName string) *GoingConcernFinalConclusionTable {
	return newGoingConcernFinalConclusionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GoingConcernFinalConclusionTable with assigned table prefix
func (a GoingConcernFinalConclusionTable) WithPrefix(prefix string) *GoingConcernFinalConclusionTable {
	return newGoingConcernFinalConclusionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GoingConcernFinalConclusionTable with assigned table suffix
func (a GoingConcernFinalConclusionTable) WithSuffix(suffix string) *GoingConcernFinalConclusionTable {
	return newGoingConcernFinalConclusionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGoingConcernFinalConclusionTable(schemaName, tableName, alias string) *GoingConcernFinalConclusionTable {
	return &GoingConcernFinalConclusionTable{
		goingConcernFinalConclusionTable: newGoingConcernFinalConclusionTableImpl(schemaName, tableName, alias),
		NEW:                              newGoingConcernFinalConclusionTableImpl("", "new", ""),
	}
}

func newGoingConcernFinalConclusionTableImpl(schemaName, tableName, alias string) goingConcernFinalConclusionTable {
	var (
		IDColumn           = mysql.StringColumn("id")
		EngagementIDColumn = mysql.StringColumn("engagement_id")
		IsValidColumn      = mysql.BoolColumn("is_valid")
		allColumns         = mysql.ColumnList{IDColumn, EngagementIDColumn, IsValidColumn}
		mutableColumns     = mysql.ColumnList{EngagementIDColumn, IsValidColumn}
	)

	return goingConcernFinalConclusionTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		EngagementID: EngagementIDColumn,
		IsValid:      IsValidColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
