//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var Groups = newGroupsTable("atlas-blue", "groups", "")

type groupsTable struct {
	mysql.Table

	// Columns
	ID       mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	EntityID mysql.ColumnString // (DC2Type:guid)
	Type     mysql.ColumnString
	LovID    mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type GroupsTable struct {
	groupsTable

	NEW groupsTable
}

// AS creates new GroupsTable with assigned alias
func (a GroupsTable) AS(alias string) *GroupsTable {
	return newGroupsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GroupsTable with assigned schema name
func (a GroupsTable) FromSchema(schemaName string) *GroupsTable {
	return newGroupsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GroupsTable with assigned table prefix
func (a GroupsTable) WithPrefix(prefix string) *GroupsTable {
	return newGroupsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GroupsTable with assigned table suffix
func (a GroupsTable) WithSuffix(suffix string) *GroupsTable {
	return newGroupsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGroupsTable(schemaName, tableName, alias string) *GroupsTable {
	return &GroupsTable{
		groupsTable: newGroupsTableImpl(schemaName, tableName, alias),
		NEW:         newGroupsTableImpl("", "new", ""),
	}
}

func newGroupsTableImpl(schemaName, tableName, alias string) groupsTable {
	var (
		IDColumn       = mysql.StringColumn("id")
		EntityIDColumn = mysql.StringColumn("entity_id")
		TypeColumn     = mysql.StringColumn("type")
		LovIDColumn    = mysql.IntegerColumn("lov_id")
		allColumns     = mysql.ColumnList{IDColumn, EntityIDColumn, TypeColumn, LovIDColumn}
		mutableColumns = mysql.ColumnList{EntityIDColumn, TypeColumn, LovIDColumn}
	)

	return groupsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:       IDColumn,
		EntityID: EntityIDColumn,
		Type:     TypeColumn,
		LovID:    LovIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
