//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var HubSubSectors = newHubSubSectorsTable("atlas-blue", "hub_sub_sectors", "")

type hubSubSectorsTable struct {
	mysql.Table

	// Columns
	ID             mysql.ColumnInteger
	LocalPackageID mysql.ColumnString
	ItemID         mysql.ColumnString
	Translations   mysql.ColumnString // (DC2Type:json)
	Acronym        mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type HubSubSectorsTable struct {
	hubSubSectorsTable

	NEW hubSubSectorsTable
}

// AS creates new HubSubSectorsTable with assigned alias
func (a HubSubSectorsTable) AS(alias string) *HubSubSectorsTable {
	return newHubSubSectorsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new HubSubSectorsTable with assigned schema name
func (a HubSubSectorsTable) FromSchema(schemaName string) *HubSubSectorsTable {
	return newHubSubSectorsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new HubSubSectorsTable with assigned table prefix
func (a HubSubSectorsTable) WithPrefix(prefix string) *HubSubSectorsTable {
	return newHubSubSectorsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new HubSubSectorsTable with assigned table suffix
func (a HubSubSectorsTable) WithSuffix(suffix string) *HubSubSectorsTable {
	return newHubSubSectorsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newHubSubSectorsTable(schemaName, tableName, alias string) *HubSubSectorsTable {
	return &HubSubSectorsTable{
		hubSubSectorsTable: newHubSubSectorsTableImpl(schemaName, tableName, alias),
		NEW:                newHubSubSectorsTableImpl("", "new", ""),
	}
}

func newHubSubSectorsTableImpl(schemaName, tableName, alias string) hubSubSectorsTable {
	var (
		IDColumn             = mysql.IntegerColumn("id")
		LocalPackageIDColumn = mysql.StringColumn("local_package_id")
		ItemIDColumn         = mysql.StringColumn("item_id")
		TranslationsColumn   = mysql.StringColumn("translations")
		AcronymColumn        = mysql.StringColumn("acronym")
		allColumns           = mysql.ColumnList{IDColumn, LocalPackageIDColumn, ItemIDColumn, TranslationsColumn, AcronymColumn}
		mutableColumns       = mysql.ColumnList{LocalPackageIDColumn, ItemIDColumn, TranslationsColumn, AcronymColumn}
	)

	return hubSubSectorsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		LocalPackageID: LocalPackageIDColumn,
		ItemID:         ItemIDColumn,
		Translations:   TranslationsColumn,
		Acronym:        AcronymColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
