//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var HubEngagementTypes = newHubEngagementTypesTable("atlas-blue", "hub_engagement_types", "")

type hubEngagementTypesTable struct {
	mysql.Table

	// Columns
	ID             mysql.ColumnInteger
	LocalPackageID mysql.ColumnString
	ItemID         mysql.ColumnString
	Translations   mysql.ColumnString // (DC2Type:json)
	Acronym        mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type HubEngagementTypesTable struct {
	hubEngagementTypesTable

	NEW hubEngagementTypesTable
}

// AS creates new HubEngagementTypesTable with assigned alias
func (a HubEngagementTypesTable) AS(alias string) *HubEngagementTypesTable {
	return newHubEngagementTypesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new HubEngagementTypesTable with assigned schema name
func (a HubEngagementTypesTable) FromSchema(schemaName string) *HubEngagementTypesTable {
	return newHubEngagementTypesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new HubEngagementTypesTable with assigned table prefix
func (a HubEngagementTypesTable) WithPrefix(prefix string) *HubEngagementTypesTable {
	return newHubEngagementTypesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new HubEngagementTypesTable with assigned table suffix
func (a HubEngagementTypesTable) WithSuffix(suffix string) *HubEngagementTypesTable {
	return newHubEngagementTypesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newHubEngagementTypesTable(schemaName, tableName, alias string) *HubEngagementTypesTable {
	return &HubEngagementTypesTable{
		hubEngagementTypesTable: newHubEngagementTypesTableImpl(schemaName, tableName, alias),
		NEW:                     newHubEngagementTypesTableImpl("", "new", ""),
	}
}

func newHubEngagementTypesTableImpl(schemaName, tableName, alias string) hubEngagementTypesTable {
	var (
		IDColumn             = mysql.IntegerColumn("id")
		LocalPackageIDColumn = mysql.StringColumn("local_package_id")
		ItemIDColumn         = mysql.StringColumn("item_id")
		TranslationsColumn   = mysql.StringColumn("translations")
		AcronymColumn        = mysql.StringColumn("acronym")
		allColumns           = mysql.ColumnList{IDColumn, LocalPackageIDColumn, ItemIDColumn, TranslationsColumn, AcronymColumn}
		mutableColumns       = mysql.ColumnList{LocalPackageIDColumn, ItemIDColumn, TranslationsColumn, AcronymColumn}
	)

	return hubEngagementTypesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		LocalPackageID: LocalPackageIDColumn,
		ItemID:         ItemIDColumn,
		Translations:   TranslationsColumn,
		Acronym:        AcronymColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
