//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var HubSectors = newHubSectorsTable("atlas-blue", "hub_sectors", "")

type hubSectorsTable struct {
	mysql.Table

	// Columns
	ID             mysql.ColumnInteger
	LocalPackageID mysql.ColumnString
	ItemID         mysql.ColumnString
	Translations   mysql.ColumnString // (DC2Type:json)
	Acronym        mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type HubSectorsTable struct {
	hubSectorsTable

	NEW hubSectorsTable
}

// AS creates new HubSectorsTable with assigned alias
func (a HubSectorsTable) AS(alias string) *HubSectorsTable {
	return newHubSectorsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new HubSectorsTable with assigned schema name
func (a HubSectorsTable) FromSchema(schemaName string) *HubSectorsTable {
	return newHubSectorsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new HubSectorsTable with assigned table prefix
func (a HubSectorsTable) WithPrefix(prefix string) *HubSectorsTable {
	return newHubSectorsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new HubSectorsTable with assigned table suffix
func (a HubSectorsTable) WithSuffix(suffix string) *HubSectorsTable {
	return newHubSectorsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newHubSectorsTable(schemaName, tableName, alias string) *HubSectorsTable {
	return &HubSectorsTable{
		hubSectorsTable: newHubSectorsTableImpl(schemaName, tableName, alias),
		NEW:             newHubSectorsTableImpl("", "new", ""),
	}
}

func newHubSectorsTableImpl(schemaName, tableName, alias string) hubSectorsTable {
	var (
		IDColumn             = mysql.IntegerColumn("id")
		LocalPackageIDColumn = mysql.StringColumn("local_package_id")
		ItemIDColumn         = mysql.StringColumn("item_id")
		TranslationsColumn   = mysql.StringColumn("translations")
		AcronymColumn        = mysql.StringColumn("acronym")
		allColumns           = mysql.ColumnList{IDColumn, LocalPackageIDColumn, ItemIDColumn, TranslationsColumn, AcronymColumn}
		mutableColumns       = mysql.ColumnList{LocalPackageIDColumn, ItemIDColumn, TranslationsColumn, AcronymColumn}
	)

	return hubSectorsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		LocalPackageID: LocalPackageIDColumn,
		ItemID:         ItemIDColumn,
		Translations:   TranslationsColumn,
		Acronym:        AcronymColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
