//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var HubTypeOfServices = newHubTypeOfServicesTable("atlas-blue", "hub_type_of_services", "")

type hubTypeOfServicesTable struct {
	mysql.Table

	// Columns
	ID             mysql.ColumnInteger
	LocalPackageID mysql.ColumnString
	ItemID         mysql.ColumnString
	Translations   mysql.ColumnString // (DC2Type:json)
	Acronym        mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type HubTypeOfServicesTable struct {
	hubTypeOfServicesTable

	NEW hubTypeOfServicesTable
}

// AS creates new HubTypeOfServicesTable with assigned alias
func (a HubTypeOfServicesTable) AS(alias string) *HubTypeOfServicesTable {
	return newHubTypeOfServicesTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new HubTypeOfServicesTable with assigned schema name
func (a HubTypeOfServicesTable) FromSchema(schemaName string) *HubTypeOfServicesTable {
	return newHubTypeOfServicesTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new HubTypeOfServicesTable with assigned table prefix
func (a HubTypeOfServicesTable) WithPrefix(prefix string) *HubTypeOfServicesTable {
	return newHubTypeOfServicesTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new HubTypeOfServicesTable with assigned table suffix
func (a HubTypeOfServicesTable) WithSuffix(suffix string) *HubTypeOfServicesTable {
	return newHubTypeOfServicesTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newHubTypeOfServicesTable(schemaName, tableName, alias string) *HubTypeOfServicesTable {
	return &HubTypeOfServicesTable{
		hubTypeOfServicesTable: newHubTypeOfServicesTableImpl(schemaName, tableName, alias),
		NEW:                    newHubTypeOfServicesTableImpl("", "new", ""),
	}
}

func newHubTypeOfServicesTableImpl(schemaName, tableName, alias string) hubTypeOfServicesTable {
	var (
		IDColumn             = mysql.IntegerColumn("id")
		LocalPackageIDColumn = mysql.StringColumn("local_package_id")
		ItemIDColumn         = mysql.StringColumn("item_id")
		TranslationsColumn   = mysql.StringColumn("translations")
		AcronymColumn        = mysql.StringColumn("acronym")
		allColumns           = mysql.ColumnList{IDColumn, LocalPackageIDColumn, ItemIDColumn, TranslationsColumn, AcronymColumn}
		mutableColumns       = mysql.ColumnList{LocalPackageIDColumn, ItemIDColumn, TranslationsColumn, AcronymColumn}
	)

	return hubTypeOfServicesTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		LocalPackageID: LocalPackageIDColumn,
		ItemID:         ItemIDColumn,
		Translations:   TranslationsColumn,
		Acronym:        AcronymColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
