//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var ItRisks = newItRisksTable("atlas-blue", "it_risks", "")

type itRisksTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	EngagementID mysql.ColumnString // (DC2Type:guid)
	NodeID       mysql.ColumnString
	Name         mysql.ColumnString
	SourceID     mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type ItRisksTable struct {
	itRisksTable

	NEW itRisksTable
}

// AS creates new ItRisksTable with assigned alias
func (a ItRisksTable) AS(alias string) *ItRisksTable {
	return newItRisksTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new ItRisksTable with assigned schema name
func (a ItRisksTable) FromSchema(schemaName string) *ItRisksTable {
	return newItRisksTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new ItRisksTable with assigned table prefix
func (a ItRisksTable) WithPrefix(prefix string) *ItRisksTable {
	return newItRisksTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new ItRisksTable with assigned table suffix
func (a ItRisksTable) WithSuffix(suffix string) *ItRisksTable {
	return newItRisksTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newItRisksTable(schemaName, tableName, alias string) *ItRisksTable {
	return &ItRisksTable{
		itRisksTable: newItRisksTableImpl(schemaName, tableName, alias),
		NEW:          newItRisksTableImpl("", "new", ""),
	}
}

func newItRisksTableImpl(schemaName, tableName, alias string) itRisksTable {
	var (
		IDColumn           = mysql.StringColumn("id")
		EngagementIDColumn = mysql.StringColumn("engagement_id")
		NodeIDColumn       = mysql.StringColumn("node_id")
		NameColumn         = mysql.StringColumn("name")
		SourceIDColumn     = mysql.StringColumn("source_id")
		allColumns         = mysql.ColumnList{IDColumn, EngagementIDColumn, NodeIDColumn, NameColumn, SourceIDColumn}
		mutableColumns     = mysql.ColumnList{EngagementIDColumn, NodeIDColumn, NameColumn, SourceIDColumn}
	)

	return itRisksTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		EngagementID: EngagementIDColumn,
		NodeID:       NodeIDColumn,
		Name:         NameColumn,
		SourceID:     SourceIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
