//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var MasterEntitiesAuditTrails = newMasterEntitiesAuditTrailsTable("atlas-blue", "master_entities_audit_trails", "")

type masterEntitiesAuditTrailsTable struct {
	mysql.Table

	// Columns
	ID             mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	EntityID       mysql.ColumnString // (DC2Type:guid)
	UserID         mysql.ColumnString // (DC2Type:guid)
	OccurredAt     mysql.ColumnTimestamp
	Tab            mysql.ColumnString
	Section        mysql.ColumnString
	Field          mysql.ColumnString
	Action         mysql.ColumnString
	OtherReference mysql.ColumnString
	PreviousValue  mysql.ColumnString
	NewValue       mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type MasterEntitiesAuditTrailsTable struct {
	masterEntitiesAuditTrailsTable

	NEW masterEntitiesAuditTrailsTable
}

// AS creates new MasterEntitiesAuditTrailsTable with assigned alias
func (a MasterEntitiesAuditTrailsTable) AS(alias string) *MasterEntitiesAuditTrailsTable {
	return newMasterEntitiesAuditTrailsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MasterEntitiesAuditTrailsTable with assigned schema name
func (a MasterEntitiesAuditTrailsTable) FromSchema(schemaName string) *MasterEntitiesAuditTrailsTable {
	return newMasterEntitiesAuditTrailsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MasterEntitiesAuditTrailsTable with assigned table prefix
func (a MasterEntitiesAuditTrailsTable) WithPrefix(prefix string) *MasterEntitiesAuditTrailsTable {
	return newMasterEntitiesAuditTrailsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MasterEntitiesAuditTrailsTable with assigned table suffix
func (a MasterEntitiesAuditTrailsTable) WithSuffix(suffix string) *MasterEntitiesAuditTrailsTable {
	return newMasterEntitiesAuditTrailsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMasterEntitiesAuditTrailsTable(schemaName, tableName, alias string) *MasterEntitiesAuditTrailsTable {
	return &MasterEntitiesAuditTrailsTable{
		masterEntitiesAuditTrailsTable: newMasterEntitiesAuditTrailsTableImpl(schemaName, tableName, alias),
		NEW:                            newMasterEntitiesAuditTrailsTableImpl("", "new", ""),
	}
}

func newMasterEntitiesAuditTrailsTableImpl(schemaName, tableName, alias string) masterEntitiesAuditTrailsTable {
	var (
		IDColumn             = mysql.StringColumn("id")
		EntityIDColumn       = mysql.StringColumn("entity_id")
		UserIDColumn         = mysql.StringColumn("user_id")
		OccurredAtColumn     = mysql.TimestampColumn("occurred_at")
		TabColumn            = mysql.StringColumn("tab")
		SectionColumn        = mysql.StringColumn("section")
		FieldColumn          = mysql.StringColumn("field")
		ActionColumn         = mysql.StringColumn("action")
		OtherReferenceColumn = mysql.StringColumn("other_reference")
		PreviousValueColumn  = mysql.StringColumn("previous_value")
		NewValueColumn       = mysql.StringColumn("new_value")
		allColumns           = mysql.ColumnList{IDColumn, EntityIDColumn, UserIDColumn, OccurredAtColumn, TabColumn, SectionColumn, FieldColumn, ActionColumn, OtherReferenceColumn, PreviousValueColumn, NewValueColumn}
		mutableColumns       = mysql.ColumnList{EntityIDColumn, UserIDColumn, OccurredAtColumn, TabColumn, SectionColumn, FieldColumn, ActionColumn, OtherReferenceColumn, PreviousValueColumn, NewValueColumn}
	)

	return masterEntitiesAuditTrailsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:             IDColumn,
		EntityID:       EntityIDColumn,
		UserID:         UserIDColumn,
		OccurredAt:     OccurredAtColumn,
		Tab:            TabColumn,
		Section:        SectionColumn,
		Field:          FieldColumn,
		Action:         ActionColumn,
		OtherReference: OtherReferenceColumn,
		PreviousValue:  PreviousValueColumn,
		NewValue:       NewValueColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
