//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var MasterGroups = newMasterGroupsTable("atlas-blue", "master_groups", "")

type masterGroupsTable struct {
	mysql.Table

	// Columns
	ID       mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	EntityID mysql.ColumnString // (DC2Type:guid)
	Type     mysql.ColumnString
	LovID    mysql.ColumnInteger

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type MasterGroupsTable struct {
	masterGroupsTable

	NEW masterGroupsTable
}

// AS creates new MasterGroupsTable with assigned alias
func (a MasterGroupsTable) AS(alias string) *MasterGroupsTable {
	return newMasterGroupsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MasterGroupsTable with assigned schema name
func (a MasterGroupsTable) FromSchema(schemaName string) *MasterGroupsTable {
	return newMasterGroupsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MasterGroupsTable with assigned table prefix
func (a MasterGroupsTable) WithPrefix(prefix string) *MasterGroupsTable {
	return newMasterGroupsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MasterGroupsTable with assigned table suffix
func (a MasterGroupsTable) WithSuffix(suffix string) *MasterGroupsTable {
	return newMasterGroupsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMasterGroupsTable(schemaName, tableName, alias string) *MasterGroupsTable {
	return &MasterGroupsTable{
		masterGroupsTable: newMasterGroupsTableImpl(schemaName, tableName, alias),
		NEW:               newMasterGroupsTableImpl("", "new", ""),
	}
}

func newMasterGroupsTableImpl(schemaName, tableName, alias string) masterGroupsTable {
	var (
		IDColumn       = mysql.StringColumn("id")
		EntityIDColumn = mysql.StringColumn("entity_id")
		TypeColumn     = mysql.StringColumn("type")
		LovIDColumn    = mysql.IntegerColumn("lov_id")
		allColumns     = mysql.ColumnList{IDColumn, EntityIDColumn, TypeColumn, LovIDColumn}
		mutableColumns = mysql.ColumnList{EntityIDColumn, TypeColumn, LovIDColumn}
	)

	return masterGroupsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:       IDColumn,
		EntityID: EntityIDColumn,
		Type:     TypeColumn,
		LovID:    LovIDColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
