//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var MinutesOfMeetings = newMinutesOfMeetingsTable("atlas-blue", "minutes_of_meetings", "")

type minutesOfMeetingsTable struct {
	mysql.Table

	// Columns
	ID                                           mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	EngagementID                                 mysql.ColumnString // (DC2Type:guid)
	NodeID                                       mysql.ColumnString
	SubareaID                                    mysql.ColumnString
	MeetingTypeID                                mysql.ColumnString
	MeetingTitle                                 mysql.ColumnString
	MeetingDate                                  mysql.ColumnDate
	MeetingLocation                              mysql.ColumnString
	OtherMeetingAttendees                        mysql.ColumnString
	FinancialPerformanceIncludingMeasuresUsed    mysql.ColumnString
	EntityRiskAssessment                         mysql.ColumnString
	EngagementConsiderations                     mysql.ColumnString
	KnowledgeOfAnyFraud                          mysql.ColumnString
	FindingsFromAnalyticalReview                 mysql.ColumnString
	ManagementAssessmentOfTheRisk                mysql.ColumnString
	AccountingEstimatesAndDisclosures            mysql.ColumnString
	ApplicationOfTheApplicableFinancialReporting mysql.ColumnString
	HowAndWhereSusceptible                       mysql.ColumnString
	AuditApproach                                mysql.ColumnString
	ManagementProcessInIdentification            mysql.ColumnString
	LitigationAndClaims                          mysql.ColumnString
	ManagementCommunicationToTcwgFraud           mysql.ColumnString
	ConfirmComplyIsa                             mysql.ColumnBool
	ConfirmComplyIsaComment                      mysql.ColumnString
	RelatedPartyRelationshipsFromPrior           mysql.ColumnString
	AreasWhereProfessionalSkepticismDirected     mysql.ColumnString
	SusceptibilityToMaterialMisstatement         mysql.ColumnString
	DiscussionProfessionalJudgement              mysql.ColumnString
	ManagementCommunicationViewsOnBusiness       mysql.ColumnString
	SignificantTransactionsWithRelatedParties    mysql.ColumnString
	TimetableReportingRequirements               mysql.ColumnString
	SignificantTransactionsOutsideNormal         mysql.ColumnString
	EthicalIssues                                mysql.ColumnString
	GoingConcernPreliminaryAssessment            mysql.ColumnString
	GoingConcernManagementAssessment             mysql.ColumnString
	ServiceOrganizations                         mysql.ColumnString
	Fraud                                        mysql.ColumnString
	KnowledgeOfFraud                             mysql.ColumnString
	LawsRegulationsCompliance                    mysql.ColumnString
	GroupAudit                                   mysql.ColumnString
	SubsequentEvents                             mysql.ColumnString
	GroupAuditUnderstandingProcess               mysql.ColumnString
	AuditAdministrationIncludingTimetable        mysql.ColumnString
	PartnerHasDetermined                         mysql.ColumnBool
	HasOtherCategories                           mysql.ColumnBool
	Comments                                     mysql.ColumnString
	OtherCategories                              mysql.ColumnString // (DC2Type:json)
	AnyOtherBusiness                             mysql.ColumnString
	PartnerEngagementEmphasis                    mysql.ColumnString
	EthicalRequirementsAwareness                 mysql.ColumnString
	CooperationDiscussion                        mysql.ColumnString
	PartnerHasDeterminedComments                 mysql.ColumnString
	IssuesImpact                                 mysql.ColumnString
	CultureEmphasisNotes                         mysql.ColumnString

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type MinutesOfMeetingsTable struct {
	minutesOfMeetingsTable

	NEW minutesOfMeetingsTable
}

// AS creates new MinutesOfMeetingsTable with assigned alias
func (a MinutesOfMeetingsTable) AS(alias string) *MinutesOfMeetingsTable {
	return newMinutesOfMeetingsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MinutesOfMeetingsTable with assigned schema name
func (a MinutesOfMeetingsTable) FromSchema(schemaName string) *MinutesOfMeetingsTable {
	return newMinutesOfMeetingsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MinutesOfMeetingsTable with assigned table prefix
func (a MinutesOfMeetingsTable) WithPrefix(prefix string) *MinutesOfMeetingsTable {
	return newMinutesOfMeetingsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MinutesOfMeetingsTable with assigned table suffix
func (a MinutesOfMeetingsTable) WithSuffix(suffix string) *MinutesOfMeetingsTable {
	return newMinutesOfMeetingsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMinutesOfMeetingsTable(schemaName, tableName, alias string) *MinutesOfMeetingsTable {
	return &MinutesOfMeetingsTable{
		minutesOfMeetingsTable: newMinutesOfMeetingsTableImpl(schemaName, tableName, alias),
		NEW:                    newMinutesOfMeetingsTableImpl("", "new", ""),
	}
}

func newMinutesOfMeetingsTableImpl(schemaName, tableName, alias string) minutesOfMeetingsTable {
	var (
		IDColumn                                           = mysql.StringColumn("id")
		EngagementIDColumn                                 = mysql.StringColumn("engagement_id")
		NodeIDColumn                                       = mysql.StringColumn("node_id")
		SubareaIDColumn                                    = mysql.StringColumn("subarea_id")
		MeetingTypeIDColumn                                = mysql.StringColumn("meeting_type_id")
		MeetingTitleColumn                                 = mysql.StringColumn("meeting_title")
		MeetingDateColumn                                  = mysql.DateColumn("meeting_date")
		MeetingLocationColumn                              = mysql.StringColumn("meeting_location")
		OtherMeetingAttendeesColumn                        = mysql.StringColumn("other_meeting_attendees")
		FinancialPerformanceIncludingMeasuresUsedColumn    = mysql.StringColumn("financial_performance_including_measures_used")
		EntityRiskAssessmentColumn                         = mysql.StringColumn("entity_risk_assessment")
		EngagementConsiderationsColumn                     = mysql.StringColumn("engagement_considerations")
		KnowledgeOfAnyFraudColumn                          = mysql.StringColumn("knowledge_of_any_fraud")
		FindingsFromAnalyticalReviewColumn                 = mysql.StringColumn("findings_from_analytical_review")
		ManagementAssessmentOfTheRiskColumn                = mysql.StringColumn("management_assessment_of_the_risk")
		AccountingEstimatesAndDisclosuresColumn            = mysql.StringColumn("accounting_estimates_and_disclosures")
		ApplicationOfTheApplicableFinancialReportingColumn = mysql.StringColumn("application_of_the_applicable_financial_reporting")
		HowAndWhereSusceptibleColumn                       = mysql.StringColumn("how_and_where_susceptible")
		AuditApproachColumn                                = mysql.StringColumn("audit_approach")
		ManagementProcessInIdentificationColumn            = mysql.StringColumn("management_process_in_identification")
		LitigationAndClaimsColumn                          = mysql.StringColumn("litigation_and_claims")
		ManagementCommunicationToTcwgFraudColumn           = mysql.StringColumn("management_communication_to_tcwg_fraud")
		ConfirmComplyIsaColumn                             = mysql.BoolColumn("confirm_comply_isa")
		ConfirmComplyIsaCommentColumn                      = mysql.StringColumn("confirm_comply_isa_comment")
		RelatedPartyRelationshipsFromPriorColumn           = mysql.StringColumn("related_party_relationships_from_prior")
		AreasWhereProfessionalSkepticismDirectedColumn     = mysql.StringColumn("areas_where_professional_skepticism_directed")
		SusceptibilityToMaterialMisstatementColumn         = mysql.StringColumn("susceptibility_to_material_misstatement")
		DiscussionProfessionalJudgementColumn              = mysql.StringColumn("discussion_professional_judgement")
		ManagementCommunicationViewsOnBusinessColumn       = mysql.StringColumn("management_communication_views_on_business")
		SignificantTransactionsWithRelatedPartiesColumn    = mysql.StringColumn("significant_transactions_with_related_parties")
		TimetableReportingRequirementsColumn               = mysql.StringColumn("timetable_reporting_requirements")
		SignificantTransactionsOutsideNormalColumn         = mysql.StringColumn("significant_transactions_outside_normal")
		EthicalIssuesColumn                                = mysql.StringColumn("ethical_issues")
		GoingConcernPreliminaryAssessmentColumn            = mysql.StringColumn("going_concern_preliminary_assessment")
		GoingConcernManagementAssessmentColumn             = mysql.StringColumn("going_concern_management_assessment")
		ServiceOrganizationsColumn                         = mysql.StringColumn("service_organizations")
		FraudColumn                                        = mysql.StringColumn("fraud")
		KnowledgeOfFraudColumn                             = mysql.StringColumn("knowledge_of_fraud")
		LawsRegulationsComplianceColumn                    = mysql.StringColumn("laws_regulations_compliance")
		GroupAuditColumn                                   = mysql.StringColumn("group_audit")
		SubsequentEventsColumn                             = mysql.StringColumn("subsequent_events")
		GroupAuditUnderstandingProcessColumn               = mysql.StringColumn("group_audit_understanding_process")
		AuditAdministrationIncludingTimetableColumn        = mysql.StringColumn("audit_administration_including_timetable")
		PartnerHasDeterminedColumn                         = mysql.BoolColumn("partnerHasDetermined")
		HasOtherCategoriesColumn                           = mysql.BoolColumn("has_other_categories")
		CommentsColumn                                     = mysql.StringColumn("comments")
		OtherCategoriesColumn                              = mysql.StringColumn("other_categories")
		AnyOtherBusinessColumn                             = mysql.StringColumn("any_other_business")
		PartnerEngagementEmphasisColumn                    = mysql.StringColumn("partner_engagement_emphasis")
		EthicalRequirementsAwarenessColumn                 = mysql.StringColumn("ethical_requirements_awareness")
		CooperationDiscussionColumn                        = mysql.StringColumn("cooperation_discussion")
		PartnerHasDeterminedCommentsColumn                 = mysql.StringColumn("partner_has_determined_comments")
		IssuesImpactColumn                                 = mysql.StringColumn("issues_impact")
		CultureEmphasisNotesColumn                         = mysql.StringColumn("culture_emphasis_notes")
		allColumns                                         = mysql.ColumnList{IDColumn, EngagementIDColumn, NodeIDColumn, SubareaIDColumn, MeetingTypeIDColumn, MeetingTitleColumn, MeetingDateColumn, MeetingLocationColumn, OtherMeetingAttendeesColumn, FinancialPerformanceIncludingMeasuresUsedColumn, EntityRiskAssessmentColumn, EngagementConsiderationsColumn, KnowledgeOfAnyFraudColumn, FindingsFromAnalyticalReviewColumn, ManagementAssessmentOfTheRiskColumn, AccountingEstimatesAndDisclosuresColumn, ApplicationOfTheApplicableFinancialReportingColumn, HowAndWhereSusceptibleColumn, AuditApproachColumn, ManagementProcessInIdentificationColumn, LitigationAndClaimsColumn, ManagementCommunicationToTcwgFraudColumn, ConfirmComplyIsaColumn, ConfirmComplyIsaCommentColumn, RelatedPartyRelationshipsFromPriorColumn, AreasWhereProfessionalSkepticismDirectedColumn, SusceptibilityToMaterialMisstatementColumn, DiscussionProfessionalJudgementColumn, ManagementCommunicationViewsOnBusinessColumn, SignificantTransactionsWithRelatedPartiesColumn, TimetableReportingRequirementsColumn, SignificantTransactionsOutsideNormalColumn, EthicalIssuesColumn, GoingConcernPreliminaryAssessmentColumn, GoingConcernManagementAssessmentColumn, ServiceOrganizationsColumn, FraudColumn, KnowledgeOfFraudColumn, LawsRegulationsComplianceColumn, GroupAuditColumn, SubsequentEventsColumn, GroupAuditUnderstandingProcessColumn, AuditAdministrationIncludingTimetableColumn, PartnerHasDeterminedColumn, HasOtherCategoriesColumn, CommentsColumn, OtherCategoriesColumn, AnyOtherBusinessColumn, PartnerEngagementEmphasisColumn, EthicalRequirementsAwarenessColumn, CooperationDiscussionColumn, PartnerHasDeterminedCommentsColumn, IssuesImpactColumn, CultureEmphasisNotesColumn}
		mutableColumns                                     = mysql.ColumnList{EngagementIDColumn, NodeIDColumn, SubareaIDColumn, MeetingTypeIDColumn, MeetingTitleColumn, MeetingDateColumn, MeetingLocationColumn, OtherMeetingAttendeesColumn, FinancialPerformanceIncludingMeasuresUsedColumn, EntityRiskAssessmentColumn, EngagementConsiderationsColumn, KnowledgeOfAnyFraudColumn, FindingsFromAnalyticalReviewColumn, ManagementAssessmentOfTheRiskColumn, AccountingEstimatesAndDisclosuresColumn, ApplicationOfTheApplicableFinancialReportingColumn, HowAndWhereSusceptibleColumn, AuditApproachColumn, ManagementProcessInIdentificationColumn, LitigationAndClaimsColumn, ManagementCommunicationToTcwgFraudColumn, ConfirmComplyIsaColumn, ConfirmComplyIsaCommentColumn, RelatedPartyRelationshipsFromPriorColumn, AreasWhereProfessionalSkepticismDirectedColumn, SusceptibilityToMaterialMisstatementColumn, DiscussionProfessionalJudgementColumn, ManagementCommunicationViewsOnBusinessColumn, SignificantTransactionsWithRelatedPartiesColumn, TimetableReportingRequirementsColumn, SignificantTransactionsOutsideNormalColumn, EthicalIssuesColumn, GoingConcernPreliminaryAssessmentColumn, GoingConcernManagementAssessmentColumn, ServiceOrganizationsColumn, FraudColumn, KnowledgeOfFraudColumn, LawsRegulationsComplianceColumn, GroupAuditColumn, SubsequentEventsColumn, GroupAuditUnderstandingProcessColumn, AuditAdministrationIncludingTimetableColumn, PartnerHasDeterminedColumn, HasOtherCategoriesColumn, CommentsColumn, OtherCategoriesColumn, AnyOtherBusinessColumn, PartnerEngagementEmphasisColumn, EthicalRequirementsAwarenessColumn, CooperationDiscussionColumn, PartnerHasDeterminedCommentsColumn, IssuesImpactColumn, CultureEmphasisNotesColumn}
	)

	return minutesOfMeetingsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                    IDColumn,
		EngagementID:          EngagementIDColumn,
		NodeID:                NodeIDColumn,
		SubareaID:             SubareaIDColumn,
		MeetingTypeID:         MeetingTypeIDColumn,
		MeetingTitle:          MeetingTitleColumn,
		MeetingDate:           MeetingDateColumn,
		MeetingLocation:       MeetingLocationColumn,
		OtherMeetingAttendees: OtherMeetingAttendeesColumn,
		FinancialPerformanceIncludingMeasuresUsed:    FinancialPerformanceIncludingMeasuresUsedColumn,
		EntityRiskAssessment:                         EntityRiskAssessmentColumn,
		EngagementConsiderations:                     EngagementConsiderationsColumn,
		KnowledgeOfAnyFraud:                          KnowledgeOfAnyFraudColumn,
		FindingsFromAnalyticalReview:                 FindingsFromAnalyticalReviewColumn,
		ManagementAssessmentOfTheRisk:                ManagementAssessmentOfTheRiskColumn,
		AccountingEstimatesAndDisclosures:            AccountingEstimatesAndDisclosuresColumn,
		ApplicationOfTheApplicableFinancialReporting: ApplicationOfTheApplicableFinancialReportingColumn,
		HowAndWhereSusceptible:                       HowAndWhereSusceptibleColumn,
		AuditApproach:                                AuditApproachColumn,
		ManagementProcessInIdentification:            ManagementProcessInIdentificationColumn,
		LitigationAndClaims:                          LitigationAndClaimsColumn,
		ManagementCommunicationToTcwgFraud:           ManagementCommunicationToTcwgFraudColumn,
		ConfirmComplyIsa:                             ConfirmComplyIsaColumn,
		ConfirmComplyIsaComment:                      ConfirmComplyIsaCommentColumn,
		RelatedPartyRelationshipsFromPrior:           RelatedPartyRelationshipsFromPriorColumn,
		AreasWhereProfessionalSkepticismDirected:     AreasWhereProfessionalSkepticismDirectedColumn,
		SusceptibilityToMaterialMisstatement:         SusceptibilityToMaterialMisstatementColumn,
		DiscussionProfessionalJudgement:              DiscussionProfessionalJudgementColumn,
		ManagementCommunicationViewsOnBusiness:       ManagementCommunicationViewsOnBusinessColumn,
		SignificantTransactionsWithRelatedParties:    SignificantTransactionsWithRelatedPartiesColumn,
		TimetableReportingRequirements:               TimetableReportingRequirementsColumn,
		SignificantTransactionsOutsideNormal:         SignificantTransactionsOutsideNormalColumn,
		EthicalIssues:                                EthicalIssuesColumn,
		GoingConcernPreliminaryAssessment:            GoingConcernPreliminaryAssessmentColumn,
		GoingConcernManagementAssessment:             GoingConcernManagementAssessmentColumn,
		ServiceOrganizations:                         ServiceOrganizationsColumn,
		Fraud:                                        FraudColumn,
		KnowledgeOfFraud:                             KnowledgeOfFraudColumn,
		LawsRegulationsCompliance:                    LawsRegulationsComplianceColumn,
		GroupAudit:                                   GroupAuditColumn,
		SubsequentEvents:                             SubsequentEventsColumn,
		GroupAuditUnderstandingProcess:               GroupAuditUnderstandingProcessColumn,
		AuditAdministrationIncludingTimetable:        AuditAdministrationIncludingTimetableColumn,
		PartnerHasDetermined:                         PartnerHasDeterminedColumn,
		HasOtherCategories:                           HasOtherCategoriesColumn,
		Comments:                                     CommentsColumn,
		OtherCategories:                              OtherCategoriesColumn,
		AnyOtherBusiness:                             AnyOtherBusinessColumn,
		PartnerEngagementEmphasis:                    PartnerEngagementEmphasisColumn,
		EthicalRequirementsAwareness:                 EthicalRequirementsAwarenessColumn,
		CooperationDiscussion:                        CooperationDiscussionColumn,
		PartnerHasDeterminedComments:                 PartnerHasDeterminedCommentsColumn,
		IssuesImpact:                                 IssuesImpactColumn,
		CultureEmphasisNotes:                         CultureEmphasisNotesColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
