//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var OtherFslrForms = newOtherFslrFormsTable("atlas-blue", "other_fslr_forms", "")

type otherFslrFormsTable struct {
	mysql.Table

	// Columns
	ID                                                      mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	EngagementID                                            mysql.ColumnString // (DC2Type:guid)
	NodeID                                                  mysql.ColumnString
	HaveIdentifiedAnyOtherFslr                              mysql.ColumnBool
	DoYouIntendToRelyOnInternalControl                      mysql.ColumnBool
	WillSubstantiveProceduresProvideSufficientAuditEvidence mysql.ColumnBool
	HasManagementImplementedControlOverTheRisk              mysql.ColumnBool
	NeedToEmphasizeToTheEngagementTeam                      mysql.ColumnBool
	NeedToEmphasizeToTheEngagementTeamComment               mysql.ColumnString
	NeedToAssignMoreExperiencedStaff                        mysql.ColumnBool
	NeedToAssignMoreExperiencedStaffComment                 mysql.ColumnString
	NeedToProvideMoreSupervision                            mysql.ColumnBool
	NeedToProvideMoreSupervisionComment                     mysql.ColumnString
	NeedToIncorporateAdditionalElements                     mysql.ColumnBool
	NeedToIncorporateAdditionalElementsComment              mysql.ColumnString
	NeedToMakeGeneralChangesToNatureTiming                  mysql.ColumnBool
	NeedToMakeGeneralChangesToNatureTimingComment           mysql.ColumnString
	UseOfAnExpertRequired                                   mysql.ColumnBool
	Status                                                  mysql.ColumnString
	IsAtLeastOneControlEvaluatedToDi                        mysql.ColumnBool
	IsAtLeastOneControlEvaluatedToOe                        mysql.ColumnBool

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type OtherFslrFormsTable struct {
	otherFslrFormsTable

	NEW otherFslrFormsTable
}

// AS creates new OtherFslrFormsTable with assigned alias
func (a OtherFslrFormsTable) AS(alias string) *OtherFslrFormsTable {
	return newOtherFslrFormsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new OtherFslrFormsTable with assigned schema name
func (a OtherFslrFormsTable) FromSchema(schemaName string) *OtherFslrFormsTable {
	return newOtherFslrFormsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new OtherFslrFormsTable with assigned table prefix
func (a OtherFslrFormsTable) WithPrefix(prefix string) *OtherFslrFormsTable {
	return newOtherFslrFormsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new OtherFslrFormsTable with assigned table suffix
func (a OtherFslrFormsTable) WithSuffix(suffix string) *OtherFslrFormsTable {
	return newOtherFslrFormsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newOtherFslrFormsTable(schemaName, tableName, alias string) *OtherFslrFormsTable {
	return &OtherFslrFormsTable{
		otherFslrFormsTable: newOtherFslrFormsTableImpl(schemaName, tableName, alias),
		NEW:                 newOtherFslrFormsTableImpl("", "new", ""),
	}
}

func newOtherFslrFormsTableImpl(schemaName, tableName, alias string) otherFslrFormsTable {
	var (
		IDColumn                                                      = mysql.StringColumn("id")
		EngagementIDColumn                                            = mysql.StringColumn("engagement_id")
		NodeIDColumn                                                  = mysql.StringColumn("node_id")
		HaveIdentifiedAnyOtherFslrColumn                              = mysql.BoolColumn("have_identified_any_other_fslr")
		DoYouIntendToRelyOnInternalControlColumn                      = mysql.BoolColumn("do_you_intend_to_rely_on_internal_control")
		WillSubstantiveProceduresProvideSufficientAuditEvidenceColumn = mysql.BoolColumn("will_substantive_procedures_provide_sufficient_audit_evidence")
		HasManagementImplementedControlOverTheRiskColumn              = mysql.BoolColumn("has_management_implemented_control_over_the_risk")
		NeedToEmphasizeToTheEngagementTeamColumn                      = mysql.BoolColumn("need_to_emphasize_to_the_engagement_team")
		NeedToEmphasizeToTheEngagementTeamCommentColumn               = mysql.StringColumn("need_to_emphasize_to_the_engagement_team_comment")
		NeedToAssignMoreExperiencedStaffColumn                        = mysql.BoolColumn("need_to_assign_more_experienced_staff")
		NeedToAssignMoreExperiencedStaffCommentColumn                 = mysql.StringColumn("need_to_assign_more_experienced_staff_comment")
		NeedToProvideMoreSupervisionColumn                            = mysql.BoolColumn("need_to_provide_more_supervision")
		NeedToProvideMoreSupervisionCommentColumn                     = mysql.StringColumn("need_to_provide_more_supervision_comment")
		NeedToIncorporateAdditionalElementsColumn                     = mysql.BoolColumn("need_to_incorporate_additional_elements")
		NeedToIncorporateAdditionalElementsCommentColumn              = mysql.StringColumn("need_to_incorporate_additional_elements_comment")
		NeedToMakeGeneralChangesToNatureTimingColumn                  = mysql.BoolColumn("need_to_make_general_changes_to_nature_timing")
		NeedToMakeGeneralChangesToNatureTimingCommentColumn           = mysql.StringColumn("need_to_make_general_changes_to_nature_timing_comment")
		UseOfAnExpertRequiredColumn                                   = mysql.BoolColumn("useOfAnExpertRequired")
		StatusColumn                                                  = mysql.StringColumn("status")
		IsAtLeastOneControlEvaluatedToDiColumn                        = mysql.BoolColumn("is_at_least_one_control_evaluated_to_di")
		IsAtLeastOneControlEvaluatedToOeColumn                        = mysql.BoolColumn("is_at_least_one_control_evaluated_to_oe")
		allColumns                                                    = mysql.ColumnList{IDColumn, EngagementIDColumn, NodeIDColumn, HaveIdentifiedAnyOtherFslrColumn, DoYouIntendToRelyOnInternalControlColumn, WillSubstantiveProceduresProvideSufficientAuditEvidenceColumn, HasManagementImplementedControlOverTheRiskColumn, NeedToEmphasizeToTheEngagementTeamColumn, NeedToEmphasizeToTheEngagementTeamCommentColumn, NeedToAssignMoreExperiencedStaffColumn, NeedToAssignMoreExperiencedStaffCommentColumn, NeedToProvideMoreSupervisionColumn, NeedToProvideMoreSupervisionCommentColumn, NeedToIncorporateAdditionalElementsColumn, NeedToIncorporateAdditionalElementsCommentColumn, NeedToMakeGeneralChangesToNatureTimingColumn, NeedToMakeGeneralChangesToNatureTimingCommentColumn, UseOfAnExpertRequiredColumn, StatusColumn, IsAtLeastOneControlEvaluatedToDiColumn, IsAtLeastOneControlEvaluatedToOeColumn}
		mutableColumns                                                = mysql.ColumnList{EngagementIDColumn, NodeIDColumn, HaveIdentifiedAnyOtherFslrColumn, DoYouIntendToRelyOnInternalControlColumn, WillSubstantiveProceduresProvideSufficientAuditEvidenceColumn, HasManagementImplementedControlOverTheRiskColumn, NeedToEmphasizeToTheEngagementTeamColumn, NeedToEmphasizeToTheEngagementTeamCommentColumn, NeedToAssignMoreExperiencedStaffColumn, NeedToAssignMoreExperiencedStaffCommentColumn, NeedToProvideMoreSupervisionColumn, NeedToProvideMoreSupervisionCommentColumn, NeedToIncorporateAdditionalElementsColumn, NeedToIncorporateAdditionalElementsCommentColumn, NeedToMakeGeneralChangesToNatureTimingColumn, NeedToMakeGeneralChangesToNatureTimingCommentColumn, UseOfAnExpertRequiredColumn, StatusColumn, IsAtLeastOneControlEvaluatedToDiColumn, IsAtLeastOneControlEvaluatedToOeColumn}
	)

	return otherFslrFormsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                                 IDColumn,
		EngagementID:                       EngagementIDColumn,
		NodeID:                             NodeIDColumn,
		HaveIdentifiedAnyOtherFslr:         HaveIdentifiedAnyOtherFslrColumn,
		DoYouIntendToRelyOnInternalControl: DoYouIntendToRelyOnInternalControlColumn,
		WillSubstantiveProceduresProvideSufficientAuditEvidence: WillSubstantiveProceduresProvideSufficientAuditEvidenceColumn,
		HasManagementImplementedControlOverTheRisk:              HasManagementImplementedControlOverTheRiskColumn,
		NeedToEmphasizeToTheEngagementTeam:                      NeedToEmphasizeToTheEngagementTeamColumn,
		NeedToEmphasizeToTheEngagementTeamComment:               NeedToEmphasizeToTheEngagementTeamCommentColumn,
		NeedToAssignMoreExperiencedStaff:                        NeedToAssignMoreExperiencedStaffColumn,
		NeedToAssignMoreExperiencedStaffComment:                 NeedToAssignMoreExperiencedStaffCommentColumn,
		NeedToProvideMoreSupervision:                            NeedToProvideMoreSupervisionColumn,
		NeedToProvideMoreSupervisionComment:                     NeedToProvideMoreSupervisionCommentColumn,
		NeedToIncorporateAdditionalElements:                     NeedToIncorporateAdditionalElementsColumn,
		NeedToIncorporateAdditionalElementsComment:              NeedToIncorporateAdditionalElementsCommentColumn,
		NeedToMakeGeneralChangesToNatureTiming:                  NeedToMakeGeneralChangesToNatureTimingColumn,
		NeedToMakeGeneralChangesToNatureTimingComment:           NeedToMakeGeneralChangesToNatureTimingCommentColumn,
		UseOfAnExpertRequired:                                   UseOfAnExpertRequiredColumn,
		Status:                                                  StatusColumn,
		IsAtLeastOneControlEvaluatedToDi:                        IsAtLeastOneControlEvaluatedToDiColumn,
		IsAtLeastOneControlEvaluatedToOe:                        IsAtLeastOneControlEvaluatedToOeColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
