//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var RepresentationLetter = newRepresentationLetterTable("atlas-blue", "representation_letter", "")

type representationLetterTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	EngagementID mysql.ColumnString // (DC2Type:guid)
	IsValid      mysql.ColumnBool

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type RepresentationLetterTable struct {
	representationLetterTable

	NEW representationLetterTable
}

// AS creates new RepresentationLetterTable with assigned alias
func (a RepresentationLetterTable) AS(alias string) *RepresentationLetterTable {
	return newRepresentationLetterTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new RepresentationLetterTable with assigned schema name
func (a RepresentationLetterTable) FromSchema(schemaName string) *RepresentationLetterTable {
	return newRepresentationLetterTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new RepresentationLetterTable with assigned table prefix
func (a RepresentationLetterTable) WithPrefix(prefix string) *RepresentationLetterTable {
	return newRepresentationLetterTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new RepresentationLetterTable with assigned table suffix
func (a RepresentationLetterTable) WithSuffix(suffix string) *RepresentationLetterTable {
	return newRepresentationLetterTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newRepresentationLetterTable(schemaName, tableName, alias string) *RepresentationLetterTable {
	return &RepresentationLetterTable{
		representationLetterTable: newRepresentationLetterTableImpl(schemaName, tableName, alias),
		NEW:                       newRepresentationLetterTableImpl("", "new", ""),
	}
}

func newRepresentationLetterTableImpl(schemaName, tableName, alias string) representationLetterTable {
	var (
		IDColumn           = mysql.StringColumn("id")
		EngagementIDColumn = mysql.StringColumn("engagement_id")
		IsValidColumn      = mysql.BoolColumn("is_valid")
		allColumns         = mysql.ColumnList{IDColumn, EngagementIDColumn, IsValidColumn}
		mutableColumns     = mysql.ColumnList{EngagementIDColumn, IsValidColumn}
	)

	return representationLetterTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		EngagementID: EngagementIDColumn,
		IsValid:      IsValidColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
