//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var SummaryOfConclusion = newSummaryOfConclusionTable("atlas-blue", "summary_of_conclusion", "")

type summaryOfConclusionTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	EngagementID mysql.ColumnString // (DC2Type:guid)
	IsValid      mysql.ColumnBool

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type SummaryOfConclusionTable struct {
	summaryOfConclusionTable

	NEW summaryOfConclusionTable
}

// AS creates new SummaryOfConclusionTable with assigned alias
func (a SummaryOfConclusionTable) AS(alias string) *SummaryOfConclusionTable {
	return newSummaryOfConclusionTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SummaryOfConclusionTable with assigned schema name
func (a SummaryOfConclusionTable) FromSchema(schemaName string) *SummaryOfConclusionTable {
	return newSummaryOfConclusionTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SummaryOfConclusionTable with assigned table prefix
func (a SummaryOfConclusionTable) WithPrefix(prefix string) *SummaryOfConclusionTable {
	return newSummaryOfConclusionTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SummaryOfConclusionTable with assigned table suffix
func (a SummaryOfConclusionTable) WithSuffix(suffix string) *SummaryOfConclusionTable {
	return newSummaryOfConclusionTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSummaryOfConclusionTable(schemaName, tableName, alias string) *SummaryOfConclusionTable {
	return &SummaryOfConclusionTable{
		summaryOfConclusionTable: newSummaryOfConclusionTableImpl(schemaName, tableName, alias),
		NEW:                      newSummaryOfConclusionTableImpl("", "new", ""),
	}
}

func newSummaryOfConclusionTableImpl(schemaName, tableName, alias string) summaryOfConclusionTable {
	var (
		IDColumn           = mysql.StringColumn("id")
		EngagementIDColumn = mysql.StringColumn("engagement_id")
		IsValidColumn      = mysql.BoolColumn("is_valid")
		allColumns         = mysql.ColumnList{IDColumn, EngagementIDColumn, IsValidColumn}
		mutableColumns     = mysql.ColumnList{EngagementIDColumn, IsValidColumn}
	)

	return summaryOfConclusionTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		EngagementID: EngagementIDColumn,
		IsValid:      IsValidColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
