//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var SummaryOfMisstatementEmptyNode = newSummaryOfMisstatementEmptyNodeTable("atlas-blue", "summary_of_misstatement_empty_node", "")

type summaryOfMisstatementEmptyNodeTable struct {
	mysql.Table

	// Columns
	ID           mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	EngagementID mysql.ColumnString // (DC2Type:guid)
	IsValid      mysql.ColumnBool

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type SummaryOfMisstatementEmptyNodeTable struct {
	summaryOfMisstatementEmptyNodeTable

	NEW summaryOfMisstatementEmptyNodeTable
}

// AS creates new SummaryOfMisstatementEmptyNodeTable with assigned alias
func (a SummaryOfMisstatementEmptyNodeTable) AS(alias string) *SummaryOfMisstatementEmptyNodeTable {
	return newSummaryOfMisstatementEmptyNodeTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new SummaryOfMisstatementEmptyNodeTable with assigned schema name
func (a SummaryOfMisstatementEmptyNodeTable) FromSchema(schemaName string) *SummaryOfMisstatementEmptyNodeTable {
	return newSummaryOfMisstatementEmptyNodeTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new SummaryOfMisstatementEmptyNodeTable with assigned table prefix
func (a SummaryOfMisstatementEmptyNodeTable) WithPrefix(prefix string) *SummaryOfMisstatementEmptyNodeTable {
	return newSummaryOfMisstatementEmptyNodeTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new SummaryOfMisstatementEmptyNodeTable with assigned table suffix
func (a SummaryOfMisstatementEmptyNodeTable) WithSuffix(suffix string) *SummaryOfMisstatementEmptyNodeTable {
	return newSummaryOfMisstatementEmptyNodeTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newSummaryOfMisstatementEmptyNodeTable(schemaName, tableName, alias string) *SummaryOfMisstatementEmptyNodeTable {
	return &SummaryOfMisstatementEmptyNodeTable{
		summaryOfMisstatementEmptyNodeTable: newSummaryOfMisstatementEmptyNodeTableImpl(schemaName, tableName, alias),
		NEW:                                 newSummaryOfMisstatementEmptyNodeTableImpl("", "new", ""),
	}
}

func newSummaryOfMisstatementEmptyNodeTableImpl(schemaName, tableName, alias string) summaryOfMisstatementEmptyNodeTable {
	var (
		IDColumn           = mysql.StringColumn("id")
		EngagementIDColumn = mysql.StringColumn("engagement_id")
		IsValidColumn      = mysql.BoolColumn("is_valid")
		allColumns         = mysql.ColumnList{IDColumn, EngagementIDColumn, IsValidColumn}
		mutableColumns     = mysql.ColumnList{EngagementIDColumn, IsValidColumn}
	)

	return summaryOfMisstatementEmptyNodeTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:           IDColumn,
		EngagementID: EngagementIDColumn,
		IsValid:      IsValidColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
