//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/mysql"
)

var UnadjustedMisstatements = newUnadjustedMisstatementsTable("atlas-blue", "unadjusted_misstatements", "")

type unadjustedMisstatementsTable struct {
	mysql.Table

	// Columns
	ID                              mysql.ColumnString // @UUID("v4")(DC2Type:guid)
	JournalMisstatementCorrectionID mysql.ColumnString // (DC2Type:guid)
	ApplyToTb                       mysql.ColumnBool
	Deleted                         mysql.ColumnBool

	AllColumns     mysql.ColumnList
	MutableColumns mysql.ColumnList
}

type UnadjustedMisstatementsTable struct {
	unadjustedMisstatementsTable

	NEW unadjustedMisstatementsTable
}

// AS creates new UnadjustedMisstatementsTable with assigned alias
func (a UnadjustedMisstatementsTable) AS(alias string) *UnadjustedMisstatementsTable {
	return newUnadjustedMisstatementsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new UnadjustedMisstatementsTable with assigned schema name
func (a UnadjustedMisstatementsTable) FromSchema(schemaName string) *UnadjustedMisstatementsTable {
	return newUnadjustedMisstatementsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new UnadjustedMisstatementsTable with assigned table prefix
func (a UnadjustedMisstatementsTable) WithPrefix(prefix string) *UnadjustedMisstatementsTable {
	return newUnadjustedMisstatementsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new UnadjustedMisstatementsTable with assigned table suffix
func (a UnadjustedMisstatementsTable) WithSuffix(suffix string) *UnadjustedMisstatementsTable {
	return newUnadjustedMisstatementsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newUnadjustedMisstatementsTable(schemaName, tableName, alias string) *UnadjustedMisstatementsTable {
	return &UnadjustedMisstatementsTable{
		unadjustedMisstatementsTable: newUnadjustedMisstatementsTableImpl(schemaName, tableName, alias),
		NEW:                          newUnadjustedMisstatementsTableImpl("", "new", ""),
	}
}

func newUnadjustedMisstatementsTableImpl(schemaName, tableName, alias string) unadjustedMisstatementsTable {
	var (
		IDColumn                              = mysql.StringColumn("id")
		JournalMisstatementCorrectionIDColumn = mysql.StringColumn("journal_misstatement_correction_id")
		ApplyToTbColumn                       = mysql.BoolColumn("apply_to_tb")
		DeletedColumn                         = mysql.BoolColumn("deleted")
		allColumns                            = mysql.ColumnList{IDColumn, JournalMisstatementCorrectionIDColumn, ApplyToTbColumn, DeletedColumn}
		mutableColumns                        = mysql.ColumnList{JournalMisstatementCorrectionIDColumn, ApplyToTbColumn, DeletedColumn}
	)

	return unadjustedMisstatementsTable{
		Table: mysql.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                              IDColumn,
		JournalMisstatementCorrectionID: JournalMisstatementCorrectionIDColumn,
		ApplyToTb:                       ApplyToTbColumn,
		Deleted:                         DeletedColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
